console.log('hello world from ts');
var myString;
var myNumb;
var myVar;
var strArr;
var numbArr;
var myBool;
var myTuple;
var myStrNumbTuple;
var myVoid = undefined;
myString = 'Hello World' + ' I work'.slice(0, 6);
myNumb = 3;
myBool = false;
myVar = true;
strArr = ['khlhi', 'worls', 'errrr'];
numbArr = [2, 4, 5];
myTuple = ['Tuple', 2, 4, 5, 'Hello'];
myStrNumbTuple = ['Tuple', 2];
console.log(myVoid);
